<!-- jquery plugins here-->
<script src="{{ asset('assets/js/jquery-1.12.1.min.js') }}"></script>
<!-- popper js -->
<script src="{{ asset('assets/js/popper.min.js') }}"></script>
<!-- bootstrap js -->
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
<!-- easing js -->
<script src="{{ asset('assets/js/jquery.magnific-popup.js') }}"></script>
<!-- swiper js -->
<script src="{{ asset('assets/js/swiper.min.js') }}"></script>
<!-- swiper js -->
<script src="{{ asset('assets/js/masonry.pkgd.js') }}"></script>
<script src="{{ asset('assets/js/lightslider.min.js') }}"></script>
<!-- particles js -->
<script src="{{ asset('assets/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.nice-select.min.js') }}"></script>
<!-- slick js -->
<script src="{{ asset('assets/js/slick.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.counterup.min.js') }}"></script>
<script src="{{ asset('assets/js/waypoints.min.js') }}"></script>
<script src="{{ asset('assets/js/contact.js') }}"></script>
<script src="{{ asset('assets/js/jquery.ajaxchimp.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.form.js') }}"></script>
<script src="{{ asset('assets/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('assets/js/stellar.js') }}"></script>
<script src="{{ asset('assets/js/price_rangs.js') }}"></script>
<!-- custom js -->
<script src="{{ asset('assets/js/custom.js') }}"></script>
